corrected

diff --git a/.github/workflows/deploy-gh-pages.yml b/.github/workflows/deploy-gh-pages.yml
--- a/.github/workflows/deploy-gh-pages.yml
+++ b/.github/workflows/deploy-gh-pages.yml
@@ -18,10 +18,15 @@ jobs:
           cache: 'npm'
           cache-dependency-path: 'package-lock.json'
 
-      - name: Install dependencies and Build
-        run:
-          npm ci
-          npm run build
+      - name: Install dependencies
+        run: npm ci
+
+      - name: Build project
+        run: npm run build
+
+      - name: Verify dist folder exists
+        run: ls -la ./dist || (echo "ERROR: dist folder not found!" && exit 1)
+
 
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v4
